name: Lint

on:
  pull_request: {}
  push:
    branches:
    - main
    tags:
    - "*"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2

      - run: pip3 install -r requirements-dev.txt
      - run: python -m isort --recursive --diff .
      - run: python -m black --check .
      - run: python -m flake8
      - run: python -m mypy
      - run: pylint --rcfile=.pylintrc omega_omnibus/
