name: Lint and Test

on:
  pull_request: {}
  push:
    branches:
    - main
    tags:
    - "*"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'

      - run: pip3 install -r requirements-dev.txt
      - run: python -m isort --recursive --diff omega_omnibus/
      - run: python -m black --check omega_omnibus/
      - run: python -m flake8 omega_omnibus/
      - run: python -m mypy omega_omnibus/
      - run: pylint --rcfile=.pylintrc omega_omnibus/

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - run: python -m pytest
