name: Test

on:
  pull_request: {}
  push:
    branches:
    - main
    tags:
    - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - run: python -m pytest
